In [2]:
import numpy as np
import time
#!pip3 install numpy(installation)

In [3]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
size = 1_000_000

#python List
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python list time = {end - start} seconds")

#numpy arrays
np_arr = np.array(py_list)
start = time.time()
#vectorized operations 
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end - start} seconds")

Python list time = 0.11337828636169434 seconds
numpy array time = 0.00402522087097168 seconds


In [5]:
#memory
import sys
print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"Numpy array size = {np_arr.nbytes} bytes")

python list size = 8000056000000 bytes
Numpy array size = 8000000 bytes


In [6]:
#create array from lists
arr = np.array([1,2,3,4,5,6])
print(arr, type(arr), arr.dtype, arr.shape )

arr1 = np.array([1,2,3,4,5,'prime'])
print(arr1,type(arr1))
print(arr1.dtype) #data type
print(arr1.shape) #dimension


arr2D = np.array([[1,2,3],[4,5,6],[7,8,9], [5,4,5]])
print(arr2D, arr2D.shape)

[1 2 3 4 5 6] <class 'numpy.ndarray'> int64 (6,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'>
<U21
(6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [5 4 5]] (4, 3)


In [7]:
#create numpy from scratch
arr1 = np.zeros((2,3), dtype="int64") #prefill
print(arr1,arr1.shape)

arr2 = np.ones((2,3), dtype = "int64") #prefill
print(arr2, arr2.shape)

arr3 = np.full((2,3),6) #prefill with val
print(arr3, arr3.shape)

arr4 = np.eye(3, dtype = "int64") #identity matrix
print(arr4)

arr5 = np.arange(1,11,2) #ranged elements
print(arr5, arr5.shape)

arr6 = np.linspace(0,11,3) #start,end,how many element[ evenly spaced arrays ]
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[6 6 6]
 [6 6 6]] (2, 3)
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[1 3 5 7 9] (5,)
[ 0.   5.5 11. ] (3,)


In [8]:
#properties

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape) #dimensions: n x n
print(arr.size)  #total elements
print(arr.dtype)
print(arr.ndim)

(3, 3)
9
int64
2


In [9]:
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [10]:
#opeartion

arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

#Reshaping
reshaped = arr.reshape(3,2)
print(reshaped, reshaped.shape)

flattened = arr.flatten() # 2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [11]:
#Indexing
arr = np.array([1,2,3,4,5])
print(arr[3])
print(arr[0])

arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1[0][2])

4
1
3


In [12]:
#Fancy Indexing
idx = [0,1,2]
print(arr[idx])

#Boolean Indexing
print(arr[arr < 5])
print(arr[arr % 2 == 0])
print(arr[arr % 2 == 1])

[1 2 3]
[1 2 3 4]
[2 4]
[1 3 5]


In [13]:
#Slicing
arr = np.array([1,2,3,4,5])
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [14]:
#copy vs view

nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200
print(sub_list)
print(nums)
print("----------------------------------")

arr = np.array(nums)
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)

print("----------------------------------")
arr1 = np.array(nums)
sub_arr1 = arr1[1:3].copy()
print(sub_arr1)
sub_arr1[0] = 200
print(sub_arr1)
print(arr1)


[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
----------------------------------
[2 3]
[200   3]
[  1 200   3   4   5]
----------------------------------
[2 3]
[200   3]
[1 2 3 4 5]


# DATA TYPES

In [15]:
#integer
arr = np.array([1,2,3,4,5])
print(arr,arr.dtype)

[1 2 3 4 5] int64


In [16]:
#float
arr = np.array([1,2,3,4,5] , dtype = "float64")
print(arr,arr.dtype)

[1. 2. 3. 4. 5.] float64


In [17]:
#bool
arr = np.array([-1,2,3,4,0] , dtype = "bool")
print(arr,arr.dtype)

[ True  True  True  True False] bool


In [18]:
#String
arr = np.array([1,2,3,4,5,"prime"])
print(arr, arr.dtype)

['1' '2' '3' '4' '5' 'prime'] <U21


In [19]:
#complex
arr = np.array([3+5j])
arr1 = np.array([3 + 2j])
print(arr + arr1, (arr+arr1).dtype)
print(arr - arr1, (arr-arr1).dtype)

[6.+7.j] complex128
[0.+3.j] complex128


In [20]:
arr = np.array(["prime",{1,2,3},3.13])
print(arr,arr.dtype)

#numpy: homogenous

['prime' {1, 2, 3} 3.13] object


# Multi Dimensional Arrays

In [21]:
#2D array

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print("----------------------------------")

print(np.sum(arr2D))

print("----------------------------------")

print(np.sum(arr2D,axis = 0))
print(np.sum(arr2D,axis = 1))

print("----------------------------------")

print(arr2D[0:2,1:2])  #slicing in 2D array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------
45
----------------------------------
[12 15 18]
[ 6 15 24]
----------------------------------
[[2]
 [5]]


In [22]:
#3D array

arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D, arr3D.shape)

print("----------------------------------")

#indexing
print(arr3D[0,1,1])
print(arr3D[1,1,0])

print("----------------------------------")

#slicing
print(arr3D[:,0,:])
print(arr3D[:,1:,0])

print("----------------------------------")

arr3D[:,0,:] = 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
----------------------------------
4
9
----------------------------------
[[1 2]
 [7 8]]
[[ 3  5]
 [ 9 11]]
----------------------------------
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


# Vectorization & Broadcasting

In [26]:
#vectorization

arr = np.array([1,2,3,4,5])
arr1 = np.array([6,7,8,9,10])
print(arr**2)
print(arr+ 2)
print(arr + arr1)

[ 1  4  9 16 25]
[3 4 5 6 7]
[ 7  9 11 13 15]


In [32]:
#Braodcasting
arr = np.array([1,2,3,4,5])
arr1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr + arr1)
print(arr.shape,arr1.shape)

#Error
# arr3= np.array([[1,2,3,4,5,6],[1,2,3,4,5]])
# print(arr1 + arr2)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
(5,) (2, 5)


In [38]:
#NORMALIZE

arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std = np.std(arr)

normalized_arr = (arr-mean)/std
print(normalized_arr)

print(np.mean(arr))
print(np.std(arr))
print(np.sqrt(5/4))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
1.118033988749895


# Mathematical fnx

In [51]:
#Aggregation

arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [52]:
#Power

arr = np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,2))


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 1  4  9 16 25]


In [56]:
#log
arr = np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [67]:
#rounding

print(np.round(3.14,1))
#Bydefault: after point
#if 1 then after point one value after that

print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14)) #removes decimal
arr = np.array([1,-1,2,2,4,-4,3,3])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr)) #positive



3.1
4.0
3.0
3.0
[-4 -1  1  2  3  4]
[-4 -1  1  2  2  3  3  4]
[1 1 2 2 4 4 3 3]
