In [2]:
import numpy as np
import time
#!pip3 install numpy(installation)

In [3]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
size = 1_000_000

#python List
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python list time = {end - start} seconds")

#numpy arrays
np_arr = np.array(py_list)
start = time.time()
#vectorized operations 
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end - start} seconds")

Python list time = 0.10148859024047852 seconds
numpy array time = 0.0036859512329101562 seconds


In [5]:
#memory
import sys
print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"Numpy array size = {np_arr.nbytes} bytes")

python list size = 8000056000000 bytes
Numpy array size = 8000000 bytes


In [6]:
#create array from lists
arr = np.array([1,2,3,4,5,6])
print(arr, type(arr), arr.dtype, arr.shape )

arr1 = np.array([1,2,3,4,5,'prime'])
print(arr1,type(arr1))
print(arr1.dtype) #data type
print(arr1.shape) #dimension


arr2D = np.array([[1,2,3],[4,5,6],[7,8,9], [5,4,5]])
print(arr2D, arr2D.shape)

[1 2 3 4 5 6] <class 'numpy.ndarray'> int64 (6,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'>
<U21
(6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [5 4 5]] (4, 3)


In [7]:
#create numpy from scratch
arr1 = np.zeros((2,3), dtype="int64") #prefill
print(arr1,arr1.shape)

arr2 = np.ones((2,3), dtype = "int64") #prefill
print(arr2, arr2.shape)

arr3 = np.full((2,3),6) #prefill with val
print(arr3, arr3.shape)

arr4 = np.eye(3, dtype = "int64") #identity matrix
print(arr4)

arr5 = np.arange(1,11,2) #ranged elements
print(arr5, arr5.shape)

arr6 = np.linspace(0,11,3) #start,end,how many element[ evenly spaced arrays ]
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[6 6 6]
 [6 6 6]] (2, 3)
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[1 3 5 7 9] (5,)
[ 0.   5.5 11. ] (3,)


In [8]:
#properties

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape) #dimensions: n x n
print(arr.size)  #total elements
print(arr.dtype)
print(arr.ndim)

(3, 3)
9
int64
2


In [10]:
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [14]:
#opeartion

arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

#Reshaping
reshaped = arr.reshape(3,2)
print(reshaped, reshaped.shape)

flattened = arr.flatten() # 2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [17]:
#Indexing
arr = np.array([1,2,3,4,5])
print(arr[3])
print(arr[0])

arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1[0][2])

4
1
3


In [22]:
#Fancy Indexing
idx = [0,1,2]
print(arr[idx])

#Boolean Indexing
print(arr[arr < 5])
print(arr[arr % 2 == 0])
print(arr[arr % 2 == 1])

[1 2 3]
[1 2 3 4]
[2 4]
[1 3 5]


In [27]:
#Slicing
arr = np.array([1,2,3,4,5])
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [40]:
#copy vs view

nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200
print(sub_list)
print(nums)
print("----------------------------------")

arr = np.array(nums)
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)

print("----------------------------------")
arr1 = np.array(nums)
sub_arr1 = arr1[1:3].copy()
print(sub_arr1)
sub_arr1[0] = 200
print(sub_arr1)
print(arr1)


[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
----------------------------------
[2 3]
[200   3]
[  1 200   3   4   5]
----------------------------------
[2 3]
[200   3]
[1 2 3 4 5]


# DATA TYPES

In [41]:
arr = np.array([1,2,3,4,5])
print(arr,arr.dtype)

[1 2 3 4 5] int64


In [42]:
arr = np.array([1,2,3,4,5] , dtype = "float64")
print(arr,arr.dtype)

[1. 2. 3. 4. 5.] float64
