In [ ]:
import numpy as np
import time
#!pip3 install numpy(installation)

In [6]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [15]:
size = 1_000_000

#python List
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python list time = {end - start} seconds")

#numpy arrays
np_arr = np.array(py_list)
start = time.time()
#vectorized operations 
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end - start} seconds")

Python list time = 1.6887047290802002 seconds
numpy array time = 0.11758613586425781 seconds


In [17]:
#memory
import sys
print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"python list size = {np_arr.nbytes} bytes")

python list size = 8000056000000 bytes
python list size = 8000000 bytes


In [28]:
#create array from lists
arr = np.array([1,2,3,4,5,6])
print(arr, type(arr), arr.dtype, arr.shape )

arr1 = np.array([1,2,3,4,5,'prime'])
print(arr1,type(arr1))
print(arr1.dtype) #data type
print(arr1.shape) #dimension


arr2D = np.array([[1,2,3],[4,5,6],[7,8,9], [5,4,5]])
print(arr2D, arr2D.shape)

[1 2 3 4 5 6] <class 'numpy.ndarray'> int64 (6,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'>
<U21
(6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [5 4 5]] (4, 3)


In [44]:
#create numpy from scratch
arr1 = np.zeros((2,3), dtype="int64") #prefill
print(arr1,arr1.shape)

arr2 = np.ones((2,3), dtype = "int64") #prefill
print(arr2, arr2.shape)

arr3 = np.full((2,3),6) #prefill with val
print(arr3, arr3.shape)

arr4 = np.eye(3, dtype = "int64") #identity matrix
print(arr4)

arr5 = np.arange(1,11,2) #ranged elements
print(arr5, arr5.shape)

arr6 = np.linspace(0,11,3) #start,end,how many element[ evenly spaced arrays ]
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[6 6 6]
 [6 6 6]] (2, 3)
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[1 3 5 7 9] (5,)
[ 0.   5.5 11. ] (3,)
